[project]
name = "respostas-canonicas"
version = "0.1.0"
description = "Comparar diferentes mÃ©todos de obter respostas canÃ´nicas a partir de perguntas parecidas"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
